// Solo strings para guardar en el form
export const leadCampaigns = [
  "JC_CAMPAÑA_LEADS_BUYERS | 0925",
  "RENTA | JC | 2310",
  "RENTA | JC | MIDFIELD | 1211",
  "VM - Buyer Video 2 | Lead Generation | 0113",
  "LG | BUYER | 0119",
  "JC | LEADS | LG | 0119 | SELLERS",
  "7512 Barkentine Street - Lead Generation - 2010",
  "[AFF - LISTADO DE CASAS_327K - ESPAÑOL]_INTERESES",
  "2008 Summit Pointe Drive, Las Vegas, Nevada 89117",
  "CAMPAÑA_LG_LISTINGS_1301",
  "JC_2801_PROGRAMAS_DE_AYUDA_DOWNPAYMENT",
  "CAMPAÑA_RTG_TEST",
  "CAMPAÑA_LG_GUÍA_PRIMEROS_COMPRADORES",
  "LISTA_DE_PROPIEDADES_IMAGENES_ACTUALIZADAS_042123",
  "LISTA_DE_PROPIEDADES_PISCINAS_IMAGENES_ACTUALIZADAS_0450823 - FB MEETING",
  "JC_CAMPAÑA_CASAS_LG_050523",
  "CAMAPAÑA_LISTADO_350K_LEADS_GENERATION",
  "CAMPAÑA_LISTADO_350K_LEADS_GENERATION",
  "CAMPAÑA_JC_LEADS_1910",
  "CAMPAÑA_0%_DOWN_PAYMENT_JC_MEETING_2510",
  "CAMPAÑA_5%_DOWN_PAYMENT_JC_MEETING_2510",
  "LISTA_DE_CASAS_500K_NEW_PLACEMENTS_+AUDIENCE_11/03/23",
  "LISTA_DE_PROPIEDADES_IMAGENES_ACTUALIZADAS_EXCLUSIONES_STRIP",
  "LG_CALIFORNIA_11072023",
  "LISTA_DE_Casas_345k_EXCLUSIONES_STRIP",
  "LG_CALIFORNIA_11072023_RTG",
  "LISTA_DE_PROPIEDADES_IMAGENES_ACTUALIZADAS_042123_RTG",
  "JC_CAMPAÑA_CASAS_LG_050523_RTG",
  "LISTA_DE_Casas_345k_EXCLUSIONES_STRIP_RTG",
  "JC_MEETING_012024 - RTG - ANTIRTG",
  "JC_CASAS_RENTA",
  "JC_VIDEOS_ENTREGA_LLAVE_LG",
  "JC_CAMPAÑA_LEADS",
  "VM - Buyer Video 2 | Lead Generation | March 2025",
  "VM - Buyer Video 1 $38k | Lead Generation | March 2025",
  "JC_CAMPAÑA_LEADS_BUYERS",
  "Visionize | Buyers Lead Gen Campaign - December 2024",
  "LG_0624",
  "JC_BUYER_CAMPAIGN_0111",
  "Visionize | Image Ads | Sellers Lead Gen Campaign - November 2024",
  "Juan Carlos | PMAX | What's Your Home Worth (Spanish) | 2025-03-11 17:56:48",
  "JC_SELLERS_LEADS_06102024",
  "JC_CAMPAÑA_LEADS_SELLERS_07092024",
  "JC_SELLERS_CAMPAING_1017",
  "[Old] Visionize | CBO | Sellers Lead Gen Campaign Feb 2025",
  "Leads_seller_0104",
  "Leads_seller_0301",
  "Visionize | Sellers Lead Gen Campaign - November 2024",
  "Visionize | Flashing Image | CBO | Sellers Lead Gen Campaign Feb 2025",
  "JC_LEADS_SELLERS",
  "Visionize | Lead Gen Campaign - November 2024",
  "Visionize | Seller Video $100k | Sellers Lead Gen Campaign - March 2025 - Copy",
  "Visionize | Flashing Home Value AI Image Ads V2 | Sellers Lead Gen Campaign - March 2025",
  "Visionize | CBO | NEW GAURENTEE Sellers Lead Gen Campaign Feb 2025",
  "Visionize | CBO | NEW Sellers Lead Gen Campaign Feb 2025",
  "SELLERS_CAMPAING_JC_0210",
  "Visionize | CBO | Sellers Lead Gen Campaign Feb 2025",
  "JC_CAMPAÑA_SELLERS_0715_MEETING",
  "LEAD_GEN_RTG_COMPRADORES",
  "LEAD_GEN_ VENDEDORES",
  "JC_LEADS_WEBSITE",
  "Juan Carlos | PMAX | What's Your Home Worth | 2025-03-06 20:31:24",
  "JC | LG | BUYERS | CALIFORNIA | 0417_V2",
  "JC | LG | SELLERS | EQUITY VIDEO | 70$ | 0416",
  "JC | LG | SELLERS | GARANTÍA DE VENTA | 70$ | 0416",
  "JC | LG | SELLERS | EQUITY VIDEO | 30$ | 0416",
  "JC | LG | SELLERS | GARANTÍA DE VENTA | 30$ | 0416",
  "JC | LEADS | SELLERS | MÁXIMO VALOR | LAS VEGAS|70$",
  "JC | LEADS | SELLERS | VIDEO_JC_COMISION | LAS VEGAS|70$",
  "JC | LEADS | SELLERS | 6_COSAS_INCREMENTAR_VALOR_DE SU_CASA | LAS VEGAS|70$",
  "LEADS_SEARCH_0523_JC",
  "JC | LEADS | SELLERS | VIDEO JC + PEDRO | LAS VEGAS|70$",
  "JC | LEADS | SELLERS | VIDEO_JC | LAS VEGAS|70$",
  "JC | LEADS 0610 | SELLERS | VIDEO_JC_COMISION | LAS VEGAS|80$",
  "JC_CAMPAÑA_LEADS_BUYERS | COPY 0611|",
  "JC | LEADS 0618 | SELLERS | VIDEO_JC_COMISION | LAS VEGAS|60$",
  "VM - Buyer Video 2 | Lead Generation | June 2025",
  "JC | LG | BUYERS | CALIFORNIA | 0621",
  "JC | LG | BUYERS | CALIFORNIA | 0625",
  "VM - Buyer Video 1 $38k | Lead Generation | June 2025",
  "VM - Buyer Video 1 $38k | Lead Generation | June 2025 copy 0407",
  "JC | LEADS 0618 | SELLERS | VIDEO_JC_COMISION | LAS VEGAS|60$ | COPY 0407",
  "VM - Buyer Video 2 | Lead Generation | June 2025 COPY 0407",
  "JC | LG | SELLERS | 60$| 0715",
  "JC_CAMPAÑA_MENSAJES_28072025",
  "JC | LG | SELLERS | 80$| 0806",
  "JC | LG | SELLERS | 70$| 0814",
  "VM - Buyer Video 1 $38k | Lead Generation | AGOSTO 14",
  "VM - Buyer Video 2 | Lead Generation | AGOSTO 14",
  "JC_MENSAJES_SELLERS_1208",
  "VM - Buyer Video 2 | Lead Generation | AGOSTO 27",
  "JC_CAMPAÑA_LEADS_BUYERS | COPY 0916",
  "JC | LG | SELLERS | $70 | 0926",
  "JC | MENSAJES | BUYER | 1709",
  "VM - Buyer Video 2 | Lead Generation | OCTUBRE 2",
  "JC | LG | SELLERS | $70 | 1006",
  "RENTA_LISET - Copy 2909",
  "VM - Buyer Video 2 | Lead Generation | OCTUBRE 8",
  "JC | LG | SELLERS | $70 | 1011",
  "JC | LISTINGS | LG | 1410",
  "VM - Buyer Video 2 | Lead Generation | OCTUBRE 14",
  "JC | LEADS | LG | 1020 | SELLERS",
  "JC | LG | BUYERS | CALIFORNIA | 1024",
  "LG | BUYER | 2410",
  "VM - Buyer Video 2 | Lead Generation | NOVIEMBRE 8",
  "JC | LEADS | VIDEOS NUEVOS | 1110",
  "JC | LEADS | LG | 1119 | SELLERS",
  "JC | LEADS | LG | 1125 | SELLERS",
  "VM - Buyer Video 2 | Lead Generation | NOVIEMBRE 25",
  "JC | LEADS | LG | 1210 | SELLERS",
  "VM - Buyer Video 2 | Lead Generation | 1210",
  "JC | LEADS | LG | 1227 | SELLERS",
  "Video | Buyers | 5K$ | 0122",
  "JC | LEADS | BUYERS | Taxes 2026: No cometas este error",
  "JC | LEADS | LG | 0212 | SELLERS",
  "Video | Buyers | 5K$ | 0212",
  "VM - Buyer Video 2 | Lead Generation | 0216",
  "JC | | LG | Buyers | Lista de propiedades +400K",
  "HOME VALUATION IMAGES | LEADS | LG | 0327 | SELLERS",
  "JC | MORTGAGE CALCULATOR | BUYERS",
  "Google Ads",
  "Google Local Services",
  "JC | Listas de Propiedades | BUYERS | 0518 - Copy",
  "VM - Buyer Video 2 | Lead Generation | 0518 - Copy",
  "Luis Galindo + Juan Carlos | Listas de Propiedades | BUYERS"
];


export const followUpSources = [
  "Data Base Follow Up + 3 Months",
  "Referral",
  "Reassigned Wrong Follow up",
  "Past Clients",
  "Bought with another realtor",
  "Recovering POND",
  "Facebook Ads",
  "TikTok Ads",
  "Google Ads",
  "Youtube Ads",
  "Instagram Ads",
  "Facebook Organic",
  "TikTok Organic",
  "Google Organic",
  "Youtube Organic",
  "Instagram Organic",
  "Supercasa Team Organic",
  "Univision",
  "Radio",
  "Billboard",
  "Telemundo",
  "Contacto Directo",
  "AFF Marketing",
];


